### ISSUE TITLE
Query regarding block movement

### ISSUE THREAD

**Issue by piyushK52** [m92vyas/stable-diffusion-3-T4#1]
I have a noob question to ask. In the generate_sd3_t4_image method, you are moving the blocks like this

```
move_transformer_modules(device='cuda', last_layers=400)
move_encoder3_modules(device='cpu', last_layers=250)
move_transformer_modules(device='cuda', last_layers='all')
```

why not first move the encoder to the CPU and then move the transformer modules entirely to GPU like this

```
move_encoder3_modules(device='cpu', last_layers=250)
move_transformer_modules(device='cuda', last_layers='all')
```

**Comment by m92vyas** [comment]
Hi, I designed the block movement keeping Google Colab free tier resources in mind. Colab provides 12 gb of cpu which was not enough to move sufficient no. of encoder3 layers. So i first created some space by moving last 400 layers of transformer from cpu to cuda and then moved sufficient no. of encoder3 layers(250) to cpu to create some GPU space for the entire transformer.
If you have enough cpu ram(like AWS will provide minimum 16 gb cpu with the T4 gpu) then you may skip this and move the blocks as you mentioned.

**Comment by piyushK52** [comment]
ah.. now I understand. Thanks.
